version: "3"
services:
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    links:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client:/usr/src/app
  backend:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    ports:
      - "5000:5000"
      - "9229:9229"
    command:
      - "npm"
      - "run"
      - "debug"
    volumes:
      - ./server:/usr/src/app
