version: "3"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    links:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client:/usr/src/app
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app